apiVersion: v1
kind: Namespace
metadata:
  name: protected-report-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: protected-report-app
  labels:
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
      - name: reporting
        image: quay.io/rhacs-misc/log4shell-minimal:1.2
        securityContext:
          allowPrivilegeEscalation: false
          readonlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_RAW
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: reporting-netpol
  namespace: protected-report-app
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: reporting
  policyTypes:
  - Ingress
  - Egress
