apiVersion: v1
kind: Namespace
metadata:
  name: vulnerable-node-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-node-app
  namespace: vulnerable-node-app
  labels:
    app: vulnerable-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-node-app
  template:
    metadata:
      labels:
        app: vulnerable-node-app
    spec:
      containers:
        - name: vulnerable-node-app
          image: quay.io/mfoster/vulnerable-node-app:0.2.1
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

