apiVersion: v1
kind: Namespace
metadata:
  name: dvma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvma
  namespace: dvma
  labels: 
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvma
  template:
    metadata:
      labels:
        app: dvma
    spec:
      containers:
        - name: dvma
          image: quay.io/mfoster/dvwa:latest
          command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
          stdin: true
          tty: true
