apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail-store-sample-app
  labels:
    app: checkout
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
        demo: roadshow
        repo: demo-apps
    spec:
      containers:
        - name: checkout
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: CART_SERVICE_URL
              value: "http://cart:8080"
            - name: ORDERS_SERVICE_URL
              value: "http://orders:8080"
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"

