apiVersion: v1
kind: Namespace
metadata:
  name: unprotected-api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-api-server
  namespace: unprotected-api-server
  labels:
    demo: roadshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-api-server
  template:
    metadata:
      labels:
        app: open-api-server
    spec:
      containers:
      - name: ubi
        image: redhat/ubi8:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        securityContext:
          allowPrivilegeEscalation: false
          readonlyRootFilesystem: true
        env:
        - name: DB_PASSWORD_SECRET
          value: "SECRET"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
